import json
import os

arbs = {
    "en_GB": {
        "@@locale": "en_GB",
        "appTitle": "Clear Space",
        "dashboardTitle": "Dashboard",
        "cleanupTitle": "Cleanup",
        "photosTitle": "Photos",
        "filesTitle": "Files",
        "settingsTitle": "Settings",
        "languageTitle": "Language",
        "themeTitle": "Theme",
        "systemTheme": "System Default",
        "lightTheme": "Light",
        "darkTheme": "Dark",
        "storageAccessRequired": "Storage Access Required",
        "storageAccessDesc": "Clear Space needs \"All files access\" to scan your device for duplicates, large files, and junk files.\n\nYou will be directed to System Settings to grant this permission when you tap Grant Permission.",
        "grantPermission": "Grant Permission",
        "getStarted": "Get Started",
        "next": "Next",
        "continueText": "Continue",
        "cancel": "Cancel",
        "analyze": "Analyse",
        "loading": "Loading...",
        "error": "Error",
        "success": "Success",
        "noItemsFound": "No items found",
        "itemsSelected": "{count, plural, =0{No items} =1{1 item} other{{count} items}} selected",
        "onboardingWelcome": "Welcome to the smartest way to keep your device clean, fast, and secure.",
        "onboardingFeaturesTitle": "Powerful Features",
        "onboardingFeaturesDesc": "Everything you need to manage your storage efficiently.",
        "feature1Title": "Understand your storage",
        "feature1Desc": "Get a clear visual breakdown of what's taking up space.",
        "feature2Title": "Clean safely",
        "feature2Desc": "Remove unnecessary files with safe deletion protocols.",
        "feature3Title": "Free up space",
        "feature3Desc": "Instantly find and remove junk, large files, and duplicates.",
        "termsDesc": "By continuing, you agree to our Terms of Service & Privacy Policy."
    },
    "es_419": {
        "@@locale": "es_419",
        "appTitle": "Clear Space",
        "dashboardTitle": "Panel",
        "cleanupTitle": "Limpieza",
        "photosTitle": "Fotos",
        "filesTitle": "Archivos",
        "settingsTitle": "Ajustes",
        "languageTitle": "Idioma",
        "themeTitle": "Tema",
        "systemTheme": "Auto",
        "lightTheme": "Claro",
        "darkTheme": "Oscuro",
        "storageAccessRequired": "Se requiere acceso",
        "storageAccessDesc": "Clear Space necesita \"Acceso a todos los archivos\" para buscar duplicados, archivos grandes y archivos basura en tu dispositivo.\n\nSerás dirigido a la configuración del sistema para otorgar este permiso cuando toques Conceder Permiso.",
        "grantPermission": "Conceder Permiso",
        "getStarted": "Empezar",
        "next": "Siguiente",
        "continueText": "Continuar",
        "cancel": "Cancelar",
        "analyze": "Analizar",
        "loading": "Cargando...",
        "error": "Error",
        "success": "Éxito",
        "noItemsFound": "No se encontraron elementos",
        "itemsSelected": "{count, plural, =0{Ningún elemento} =1{1 elemento} other{{count} elementos}} seleccionados",
        "onboardingWelcome": "Bienvenido a la forma más inteligente de mantener tu dispositivo limpio, rápido y seguro.",
        "onboardingFeaturesTitle": "Funciones potentes",
        "onboardingFeaturesDesc": "Todo lo que necesitas para administrar tu almacenamiento de manera eficiente.",
        "feature1Title": "Entiende tu almacenamiento",
        "feature1Desc": "Obtén un desglose visual claro de lo que está ocupando espacio.",
        "feature2Title": "Limpia de forma segura",
        "feature2Desc": "Elimina archivos innecesarios con protocolos de eliminación seguros.",
        "feature3Title": "Libera espacio",
        "feature3Desc": "Encuentra y elimina instantáneamente basura, archivos grandes y duplicados.",
        "termsDesc": "Al continuar, aceptas nuestros Términos de Servicio y Política de Privacidad."
    },
    "es_ES": {
        "@@locale": "es_ES",
        "appTitle": "Clear Space",
        "dashboardTitle": "Panel",
        "cleanupTitle": "Limpieza",
        "photosTitle": "Fotos",
        "filesTitle": "Archivos",
        "settingsTitle": "Ajustes",
        "languageTitle": "Idioma",
        "themeTitle": "Tema",
        "systemTheme": "Auto",
        "lightTheme": "Claro",
        "darkTheme": "Oscuro",
        "storageAccessRequired": "Acceso requerido",
        "storageAccessDesc": "Clear Space necesita \"Acceso a todos los archivos\" para buscar duplicados, archivos grandes y archivos basura en tu dispositivo.\n\nSe te dirigirá a los Ajustes del sistema para otorgar este permiso cuando toques Conceder acceso.",
        "grantPermission": "Conceder acceso",
        "getStarted": "Empezar",
        "next": "Siguiente",
        "continueText": "Continuar",
        "cancel": "Cancelar",
        "analyze": "Analizar",
        "loading": "Cargando...",
        "error": "Error",
        "success": "Éxito",
        "noItemsFound": "No se encontraron elementos",
        "itemsSelected": "{count, plural, =0{Ningún elemento} =1{1 elemento} other{{count} elementos}} seleccionados",
        "onboardingWelcome": "Bienvenido a la forma más inteligente de mantener tu dispositivo limpio, rápido y seguro.",
        "onboardingFeaturesTitle": "Funciones potentes",
        "onboardingFeaturesDesc": "Todo lo que necesitas para gestionar tu almacenamiento de manera eficiente.",
        "feature1Title": "Entiende tu almacenamiento",
        "feature1Desc": "Obtén un desglose visual claro de lo que está ocupando espacio.",
        "feature2Title": "Limpia de forma segura",
        "feature2Desc": "Elimina archivos innecesarios con protocolos de eliminación seguros.",
        "feature3Title": "Libera espacio",
        "feature3Desc": "Encuentra y elimina al instante basura, archivos grandes y duplicados.",
        "termsDesc": "Al continuar, aceptas nuestros Términos de servicio y Política de privacidad."
    },
    "pt_BR": {
        "@@locale": "pt_BR",
        "appTitle": "Clear Space",
        "dashboardTitle": "Painel",
        "cleanupTitle": "Limpeza",
        "photosTitle": "Fotos",
        "filesTitle": "Arquivos",
        "settingsTitle": "Configurações",
        "languageTitle": "Idioma",
        "themeTitle": "Tema",
        "systemTheme": "Padrão do Sistema",
        "lightTheme": "Claro",
        "darkTheme": "Escuro",
        "storageAccessRequired": "Acesso Necessário",
        "storageAccessDesc": "O Clear Space precisa de \"Acesso a todos os arquivos\" para verificar se há duplicatas, arquivos grandes e arquivos indesejados no seu dispositivo.\n\nVocê será direcionado para as Configurações do Sistema para conceder essa permissão.",
        "grantPermission": "Conceder Permissão",
        "getStarted": "Começar",
        "next": "Próximo",
        "continueText": "Continuar",
        "cancel": "Cancelar",
        "analyze": "Analisar",
        "loading": "Carregando...",
        "error": "Erro",
        "success": "Sucesso",
        "noItemsFound": "Nenhum item encontrado",
        "itemsSelected": "{count, plural, =0{Nenhum item} =1{1 item} other{{count} itens}} selecionados",
        "onboardingWelcome": "Bem-vindo à maneira mais inteligente de manter seu dispositivo limpo, rápido e seguro.",
        "onboardingFeaturesTitle": "Recursos Poderosos",
        "onboardingFeaturesDesc": "Tudo o que você precisa para gerenciar seu armazenamento com eficiência.",
        "feature1Title": "Entenda seu armazenamento",
        "feature1Desc": "Obtenha um detalhamento visual claro do que está ocupando espaço.",
        "feature2Title": "Limpe com segurança",
        "feature2Desc": "Remova arquivos desnecessários com protocolos de exclusão seguros.",
        "feature3Title": "Libere espaço",
        "feature3Desc": "Encontre e remova instantaneamente lixo, arquivos grandes e duplicatas.",
        "termsDesc": "Ao continuar, você concorda com nossos Termos de Serviço e Política de Privacidade."
    },
    "hi_IN": {
        "@@locale": "hi_IN",
        "appTitle": "Clear Space",
        "dashboardTitle": "डैशबोर्ड",
        "cleanupTitle": "सफाई",
        "photosTitle": "तस्वीरें",
        "filesTitle": "फ़ाइलें",
        "settingsTitle": "सेटिंग्स",
        "languageTitle": "भाषा",
        "themeTitle": "थीम",
        "systemTheme": "सिस्टम डिफ़ॉल्ट",
        "lightTheme": "हल्का",
        "darkTheme": "गहरा",
        "storageAccessRequired": "स्टोरेज एक्सेस आवश्यक",
        "storageAccessDesc": "क्लियर स्पेस को आपके डिवाइस में डुप्लिकेट, बड़ी फ़ाइलों और जंक फ़ाइलों को स्कैन करने के लिए \"सभी फ़ाइलों तक पहुंच\" की आवश्यकता है।\n\nअनुमति देने के लिए सिस्टम सेटिंग्स खुलेगी।",
        "grantPermission": "अनुमति दें",
        "getStarted": "शुरू करें",
        "next": "अगला",
        "continueText": "जारी रखें",
        "cancel": "रद्द करें",
        "analyze": "विश्लेषण करें",
        "loading": "लोड हो रहा है...",
        "error": "त्रुटि",
        "success": "सफलता",
        "noItemsFound": "कोई आइटम नहीं मिला",
        "itemsSelected": "{count, plural, =0{कोई आइटम नहीं} =1{1 आइटम} other{{count} आइटम}} चुने गए",
        "onboardingWelcome": "अपने डिवाइस को साफ़, तेज़ और सुरक्षित रखने के सबसे स्मार्ट तरीके में आपका स्वागत है।",
        "onboardingFeaturesTitle": "शक्तिशाली विशेषताएँ",
        "onboardingFeaturesDesc": "अपने स्टोरेज को कुशलतापूर्वक प्रबंधित करने के लिए आपको जो कुछ भी चाहिए।",
        "feature1Title": "अपना स्टोरेज समझें",
        "feature1Desc": "स्पष्ट दृश्य विश्लेषण प्राप्त करें कि क्या जगह घेर रहा है।",
        "feature2Title": "सुरक्षित रूप से साफ़ करें",
        "feature2Desc": "सुरक्षित हटाना प्रोटोकॉल के साथ अनावश्यक फ़ाइलों को निकालें।",
        "feature3Title": "स्थान खाली करें",
        "feature3Desc": "तुरंत जंक, बड़ी फ़ाइलें और डुप्लिकेट ढूंढें और हटा दें।",
        "termsDesc": "जारी रखकर, आप हमारी सेवा की शर्तों और गोपनीयता नीति से सहमत होते हैं।"
    },
    "id": {
        "@@locale": "id",
        "appTitle": "Clear Space",
        "dashboardTitle": "Dasbor",
        "cleanupTitle": "Pembersihan",
        "photosTitle": "Foto",
        "filesTitle": "File",
        "settingsTitle": "Pengaturan",
        "languageTitle": "Bahasa",
        "themeTitle": "Tema",
        "systemTheme": "Auto",
        "lightTheme": "Terang",
        "darkTheme": "Gelap",
        "storageAccessRequired": "Akses Penyimpanan",
        "storageAccessDesc": "Clear Space memerlukan \"Akses ke semua file\" untuk memindai perangkat Anda dari file duplikat, file besar, dan file sampah.\n\nAnda akan diarahkan ke Pengaturan Sistem untuk memberikan izin ini.",
        "grantPermission": "Berikan Izin",
        "getStarted": "Mulai",
        "next": "Berikutnya",
        "continueText": "Lanjutkan",
        "cancel": "Batal",
        "analyze": "Analisis",
        "loading": "Memuat...",
        "error": "Kesalahan",
        "success": "Sukses",
        "noItemsFound": "Tidak ada file",
        "itemsSelected": "{count, plural, =0{0 item} =1{1 item} other{{count} item}} dipilih",
        "onboardingWelcome": "Selamat datang di cara paling cerdas untuk menjaga ponsel Anda bersih, cepat, dan aman.",
        "onboardingFeaturesTitle": "Fitur Canggih",
        "onboardingFeaturesDesc": "Semua yang Anda butuhkan untuk mengelola penyimpanan.",
        "feature1Title": "Pahami penyimpanan Anda",
        "feature1Desc": "Dapatkan rincian visual yang jelas tentang apa yang menghabiskan ruang.",
        "feature2Title": "Bersihkan dengan aman",
        "feature2Desc": "Hapus file yang tidak perlu dengan penghapusan yang aman.",
        "feature3Title": "Kosongkan ruang",
        "feature3Desc": "Temukan dan hapus file sampah, file besar, dan duplikat.",
        "termsDesc": "Dengan melanjutkan, Anda menyetujui Ketentuan & Privasi kami."
    },
    "tr_TR": {
        "@@locale": "tr_TR",
        "appTitle": "Clear Space",
        "dashboardTitle": "Panel",
        "cleanupTitle": "Temizle",
        "photosTitle": "Fotoğraflar",
        "filesTitle": "Dosyalar",
        "settingsTitle": "Ayarlar",
        "languageTitle": "Dil",
        "themeTitle": "Tema",
        "systemTheme": "Sistem Varsayılanı",
        "lightTheme": "Açık",
        "darkTheme": "Koyu",
        "storageAccessRequired": "Erişim Gerekli",
        "storageAccessDesc": "Clear Space'in cihazınızda kopyaları, büyük dosyaları ve çöp dosyaları taramak için \"Tüm dosyalara erişim\" iznine ihtiyacı var.\n\nİzin vermek için ayarlara yönlendirileceksiniz.",
        "grantPermission": "İzin Ver",
        "getStarted": "Başla",
        "next": "İleri",
        "continueText": "Devam",
        "cancel": "İptal",
        "analyze": "Analiz Et",
        "loading": "Yükleniyor...",
        "error": "Hata",
        "success": "Başarılı",
        "noItemsFound": "Öğe bulunamadı",
        "itemsSelected": "{count, plural, =0{Öğe yok} =1{1 öğe} other{{count} öğe}} seçildi",
        "onboardingWelcome": "Cihazınızı temiz, hızlı ve güvenli tutmanın en akıllı yoluna hoş geldiniz.",
        "onboardingFeaturesTitle": "Güçlü Özellikler",
        "onboardingFeaturesDesc": "Depolamanızı verimli bir şekilde yönetmek için ihtiyacınız olan her şey.",
        "feature1Title": "Depolamanızı anlayın",
        "feature1Desc": "Neyin yer kapladığına dair net bir görsel döküm alın.",
        "feature2Title": "Güvenle temizleyin",
        "feature2Desc": "Gereksiz dosyaları güvenli silme protokolleriyle kaldırın.",
        "feature3Title": "Yer açın",
        "feature3Desc": "Çöpleri, büyük dosyaları ve kopyaları anında bulun ve silin.",
        "termsDesc": "Devam ederek, Gizlilik Politikamızı kabul etmiş olursunuz."
    },
    "de_DE": {
        "@@locale": "de_DE",
        "appTitle": "Clear Space",
        "dashboardTitle": "Dashboard",
        "cleanupTitle": "Bereinigen",
        "photosTitle": "Fotos",
        "filesTitle": "Dateien",
        "settingsTitle": "Einstellungen",
        "languageTitle": "Sprache",
        "themeTitle": "Design",
        "systemTheme": "Auto",
        "lightTheme": "Hell",
        "darkTheme": "Dunkel",
        "storageAccessRequired": "Zugriff erforderlich",
        "storageAccessDesc": "Clear Space benötigt den \"Zugriff auf alle Dateien\", um Ihr Gerät auf Duplikate, große Dateien und Junk-Dateien zu scannen.\n\nSie werden zu den Einstellungen weitergeleitet, um dies zu erlauben.",
        "grantPermission": "Erlauben",
        "getStarted": "Loslegen",
        "next": "Weiter",
        "continueText": "Fortfahren",
        "cancel": "Abbrechen",
        "analyze": "Analysieren",
        "loading": "Laden...",
        "error": "Fehler",
        "success": "Erfolgreich",
        "noItemsFound": "Nichts gefunden",
        "itemsSelected": "{count, plural, =0{0 Elemente} =1{1 Element} other{{count} Elemente}} ausgewählt",
        "onboardingWelcome": "Der intelligenteste Weg, Ihr Gerät sauber, schnell und sicher zu halten.",
        "onboardingFeaturesTitle": "Starke Funktionen",
        "onboardingFeaturesDesc": "Alles, was Sie zur Verwaltung Ihres Speichers benötigen.",
        "feature1Title": "Speicher analysieren",
        "feature1Desc": "Visuelle Aufschlüsselung Ihres Speichers.",
        "feature2Title": "Sicher bereinigen",
        "feature2Desc": "Unnötige Dateien sicher löschen.",
        "feature3Title": "Platz schaffen",
        "feature3Desc": "Finden Sie sofort Junk, große Dateien und Duplikate.",
        "termsDesc": "Durch Fortfahren stimmen Sie den Bedingungen zu."
    },
    "fr_FR": {
        "@@locale": "fr_FR",
        "appTitle": "Clear Space",
        "dashboardTitle": "Accueil",
        "cleanupTitle": "Nettoyage",
        "photosTitle": "Photos",
        "filesTitle": "Fichiers",
        "settingsTitle": "Paramètres",
        "languageTitle": "Langue",
        "themeTitle": "Thème",
        "systemTheme": "Auto",
        "lightTheme": "Clair",
        "darkTheme": "Sombre",
        "storageAccessRequired": "Accès requis",
        "storageAccessDesc": "Clear Space a besoin de \"l'accès à tous les fichiers\" pour analyser votre appareil à la recherche de doublons, de fichiers volumineux et de fichiers indésirables.\n\nVous serez redirigé vers les paramètres du système pour accorder cette autorisation.",
        "grantPermission": "Accorder",
        "getStarted": "Commencer",
        "next": "Suivant",
        "continueText": "Continuer",
        "cancel": "Annuler",
        "analyze": "Analyser",
        "loading": "Chargement...",
        "error": "Erreur",
        "success": "Succès",
        "noItemsFound": "Aucun fichier",
        "itemsSelected": "{count, plural, =0{0 élément} =1{1 élément} other{{count} éléments}} sélectionnés",
        "onboardingWelcome": "Le moyen le plus intelligent de garder votre appareil propre et rapide.",
        "onboardingFeaturesTitle": "Fonctionnalités puissantes",
        "onboardingFeaturesDesc": "Tout ce dont vous avez besoin pour gérer votre espace de stockage.",
        "feature1Title": "Comprendre votre stockage",
        "feature1Desc": "Répartition visuelle claire de ce qui prend de la place.",
        "feature2Title": "Nettoyer en toute sécurité",
        "feature2Desc": "Supprimez les fichiers inutiles de manière sécurisée.",
        "feature3Title": "Libérer de l'espace",
        "feature3Desc": "Trouvez et supprimez instantanément les fichiers indésirables.",
        "termsDesc": "En continuant, vous acceptez nos conditions d'utilisation."
    },
    "fil": {
        "@@locale": "fil",
        "appTitle": "Clear Space",
        "dashboardTitle": "Dashboard",
        "cleanupTitle": "Linisin",
        "photosTitle": "Mga Larawan",
        "filesTitle": "Mga File",
        "settingsTitle": "Mga Setting",
        "languageTitle": "Wika",
        "themeTitle": "Tema",
        "systemTheme": "Auto",
        "lightTheme": "Puti",
        "darkTheme": "Itim",
        "storageAccessRequired": "Kailangan ng Access",
        "storageAccessDesc": "Kailangan ng Clear Space ang \"Access sa lahat ng file\" upang masuri ang iyong device para sa mga duplicate, malalaking file, at mga basura.\n\nDadalhin ka sa Mga Setting upang ibigay ang pahintulot na ito.",
        "grantPermission": "Ibigay ang Pahintulot",
        "getStarted": "Magsimula",
        "next": "Susunod",
        "continueText": "Magpatuloy",
        "cancel": "Kanselahin",
        "analyze": "Suriin",
        "loading": "Naglo-load...",
        "error": "Error",
        "success": "Tagumpay",
        "noItemsFound": "Walang nakita",
        "itemsSelected": "{count, plural, =0{0 aytem} =1{1 aytem} other{{count} aytem}} ang napili",
        "onboardingWelcome": "Maligayang pagdating sa pinakamatalinong paraan upang panatilihing malinis ang iyong cell phone.",
        "onboardingFeaturesTitle": "Makapangyarihang Tampok",
        "onboardingFeaturesDesc": "Lahat ng kailangan mo upang malinis ang storage.",
        "feature1Title": "Unawain ang storage",
        "feature1Desc": "Kumuha ng pagsusuri kung ano ang kumukuha ng espasyo.",
        "feature2Title": "Linisin nang ligtas",
        "feature2Desc": "Alisin ang mga file gamit ang ligtas na pag-delete.",
        "feature3Title": "Magbakante ng espasyo",
        "feature3Desc": "Agad na hanapin at alisin ang basura at malalaking file.",
        "termsDesc": "Sa pagpapatuloy, sumasang-ayon ka sa aming Mga Tuntunin."
    }
}

for locale, data in arbs.items():
    formatted_json = json.dumps(data, indent=2, ensure_ascii=False)
    path = os.path.join("d:\\Github\\clear-space\\lib\\l10n", f"app_{locale}.arb")
    with open(path, "w", encoding="utf-8") as f:
        f.write(formatted_json)
