import 'dart:convert';
import 'dart:io';

void main() async {
  print('Building Translation Matrix...');
  
  // Base dictionary for the 96 missing specific keys mapped to languages.
  final Map<String, Map<String, String>> matrix = {
    'es': _es(), 'es_ES': _es(), 'es_419': _es(),
    'pt': _pt(), 'pt_BR': _pt(),
    'fr': _fr(), 'fr_FR': _fr(),
    'de': _de(), 'de_DE': _de(),
    'tr': _tr(), 'tr_TR': _tr(),
    'hi': _hi(), 'hi_IN': _hi(),
    'id': _id(),
    'fil': _fil(),
  };

  final dir = Directory('lib/l10n');
  final files = await dir.list().where((f) => f.path.endsWith('.arb')).toList();
  final suffixRegex = RegExp(r'\([a-z_]{2,5}\)$', caseSensitive: false);
  
  int totalReplaced = 0;

  for (final file in files) {
    if (file is File) {
      final content = await file.readAsString();
      final Map<String, dynamic> data = jsonDecode(content);
      
      final locale = data['@@locale'] as String?;
      if (locale == null || locale == 'en' || locale == 'vi') continue;
      
      // Determine the best dictionary map for this locale (e.g. es_ES -> es)
      Map<String, String>? localDict;
      if (matrix.containsKey(locale)) {
        localDict = matrix[locale];
      } else {
        final baseCode = locale.split('_').first;
        localDict = matrix[baseCode];
      }

      int fileReplacements = 0;

      data.updateAll((key, value) {
        if (value is String && suffixRegex.hasMatch(value)) {
          if (localDict != null && localDict.containsKey(key)) {
            fileReplacements++;
            totalReplaced++;
            return localDict[key]!;
          } else {
            // Fallback: Strip the suffix, leaving clean English if no dict was provided.
            fileReplacements++;  
            totalReplaced++;
            return value.replaceAll(suffixRegex, '').trim();
          }
        }
        return value;
      });

      if (fileReplacements > 0) {
        const JsonEncoder encoder = JsonEncoder.withIndent('  ');
        await file.writeAsString(encoder.convert(data) + '\n');
        print('Updated app_$locale.arb ($fileReplacements keys)');
      }
    }
  }
  print('\nFinished. Successfully replaced and cleaned $totalReplaced legacy placeholders.');
}

Map<String, String> _es() => {
  "refreshingAppList": "Actualizando lista de aplicaciones...",
  "openingUninstaller": "Abriendo desinstalador...",
  "uninstallApp": "Desinstalar aplicación",
  "uninstall": "Desinstalar",
  "sortLargest": "Más grandes",
  "sortSmallest": "Más pequeños",
  "sortNewest": "Más recientes",
  "sortAZ": "A-Z",
  "pageNotFound": "Página no encontrada",
  "goToDashboard": "Ir al Panel",
  "deleteFilesTitle": "Eliminar archivos",
  "smartCleanupPlanTitle": "Plan de limpieza inteligente",
  "screenshotsCleanerTitle": "Limpiador de capturas",
  "tryAgain": "Reintentar",
  "appManagerTitle": "Gestor de aplicaciones",
  "searchApps": "Buscar aplicaciones...",
  "noAppsFound": "No se encontraron aplicaciones",
  "noMatchingApps": "Sin coincidencias",
  "uninstallConfirmMsg": "¿Seguro que quieres desinstalar \"{appName}\" ({size})?",
  "uninstallActionDesc": "Se eliminará la aplicación y todos sus datos.",
  "appsCount": "{count} aplicaciones",
  "appsShowingCount": "{showing} / {total} aplicaciones",
  "allClean": "¡Todo limpio!",
  "deleting": "Eliminando...",
  "deleteItemsCount": "Eliminar {count} elementos ({size})",
  "deletedCountMsg": "Eliminados {count} elementos ({size})",
  "actionCannotBeUndone": "Esta acción no se puede deshacer.",
  "cleanupBreakdown": "Resumen de limpieza",
  "smartCleanupDesc": "Conservamos automáticamente la mejor versión de tus fotos y archivos.",
  "cleaning": "Limpiando...",
  "cleanUpSize": "Liberar {size}",
  "youSavedSize": "Has ahorrado {size}",
  "youreAllSet": "¡Todo listo!",
  "noSmartCleanupItems": "No se encontraron archivos duplicados o similares.",
  "save": "Guardar",
  "keep": "MANTENER",
  "deselectAll": "Deseleccionar todo",
  "images": "Imágenes",
  "docs": "Documentos",
  "others": "Otros",
  "all": "Todos",
  "deleteConfirmMsg": "¿Seguro que quieres eliminar {count} archivos seleccionados?\n\nSe moverán a la papelera o se eliminarán definitivamente.",
  "screenshotsCount": "{count, plural, =0{Sin capturas} =1{1 captura} other{{count} capturas}}",
  "selectedCountSize": "Seleccionado: {count} ({size})",
  "deleteSelectedSize": "Eliminar selección ({size})",
  "deleteFailedGeneral": "Error al eliminar algunos elementos. Inténtalo de nuevo.",
  "systemDefault": "Por defecto",
  "light": "Claro",
  "dark": "Oscuro",
  "strictSensitivity": "Estricto (Coincidencia 95%)",
  "normalSensitivity": "Normal (Coincidencia 85%)",
  "looseSensitivity": "Flexible (Coincidencia 75%)",
  "sensitivityDesc": "Elige qué tan estricta es la aplicación al identificar fotos similares. Una configuración estricta significa que las fotos deben ser casi idénticas.",
  "strictSensitivityDesc": "Coincidencia 95% — Solo casi idénticas",
  "normalSensitivityDesc": "Coincidencia 85% — Recomendado",
  "looseSensitivityDesc": "Coincidencia 75% — Captura más variaciones",
  "sensitivityUpdated": "Límite de sensibilidad actualizado. Se aplicará en el próximo escaneo.",
  "thresholdDesc": "Los archivos por encima de este valor se marcarán para su eliminación.",
  "thresholdUpdated": "Límite de tamaño actualizado. Se aplicará en el próximo escaneo.",
  "largerThanSize": "Mayores a {size}",
  "madeWithHeart": "Hecho con ❤️ para un teléfono más limpio",
  "versionUnavailable": "Versión no disponible",
  "emailNotSupported": "No se pudo abrir el correo. Escríbenos directamente.",
  "clearSpace": "Clear Space",
  "storageDashboard": "Panel de almacenamiento",
  "junkFilesFound": "Archivos basura encontrados",
  "itemsCanBeCleaned": "{count} elementos a limpiar",
  "storageBreakdown": "Desglose de uso",
  "cleanup": "Limpiar",
  "suggestions": "Sugerencias",
  "analyzing": "Analizando...",
  "keepStorageHealthy": "Mantén tu memoria sana",
  "cleanupHeaderDesc": "Encontramos archivos que podrías eliminar para liberar espacio.",
  "percentUsed": "{percentage}% Usado",
  "scanPausedBattery": "Pausado (Batería baja)",
  "scanningPhase": "Escaneando {phase}...",
  "scanningPhasePercent": "Escaneando {phase}... ({percentage}%)",
  "calculating": "Calculando...",
  "internalStorage": "ALMACENAMIENTO",
  "free": "Libre",
  "used": "Usado",
  "total": "Total",
  "phaseDisk": "Disco",
  "phasePhotos": "Fotos",
  "phaseVideos": "Videos",
  "phaseAudio": "Audio",
  "phaseDocuments": "Docs",
  "phaseJunk": "Basura",
  "phaseFolders": "Carpetas",
  "phaseApks": "APKs",
  "phaseSimilar": "Fotos similares",
  "phaseStorage": "Memoria",
  "selectYourLanguage": "Elige tu idioma",
  "largeFilesTitle": "Archivos grandes",
  "usedSize": "{size} Usado",
  "totalSize": "{size} Total",
  "clearHistory": "Borrar historial",
  "clearHistoryConfirm": "¿Estás seguro de que quieres borrar todo el historial?",
  "clearAll": "Borrar todo",
  "cleanAllSafeItems": "Limpiar uso seguro"
};

Map<String, String> _pt() => {
  "refreshingAppList": "Atualizando lista de aplicativos...",
  "openingUninstaller": "Abrindo desinstalador...",
  "uninstallApp": "Desinstalar o aplicativo",
  "uninstall": "Desinstalar",
  "sortLargest": "Mais pesados",
  "sortSmallest": "Mais leves",
  "sortNewest": "Mais recentes",
  "sortAZ": "A-Z",
  "pageNotFound": "Página não encontrada",
  "goToDashboard": "Ir para o Painel",
  "deleteFilesTitle": "Excluir arquivos",
  "smartCleanupPlanTitle": "Plano de limpeza inteligente",
  "screenshotsCleanerTitle": "Limpeza de capturas",
  "tryAgain": "Tentar novamente",
  "appManagerTitle": "Gerenciador de Apps",
  "searchApps": "Procurar aplicativos...",
  "noAppsFound": "Nenhum aplicativo encontrado",
  "noMatchingApps": "Nenhuma correspondência",
  "uninstallConfirmMsg": "Tem certeza que deseja desinstalar \"{appName}\" ({size})?",
  "uninstallActionDesc": "Isso removerá o aplicativo e todos os dados.",
  "appsCount": "{count} aplicativos",
  "appsShowingCount": "{showing} / {total} aplicativos",
  "allClean": "Tudo limpo!",
  "deleting": "Excluindo...",
  "deleteItemsCount": "Excluir {count} itens ({size})",
  "deletedCountMsg": "{count} itens excluídos ({size})",
  "actionCannotBeUndone": "Esta ação não pode ser desfeita.",
  "cleanupBreakdown": "Resumo da Limpeza",
  "smartCleanupDesc": "Mantemos automaticamente a melhor versão de suas fotos e arquivos.",
  "cleaning": "Limpando...",
  "cleanUpSize": "Limpar {size}",
  "youSavedSize": "Você economizou {size}",
  "youreAllSet": "Tudo pronto!",
  "noSmartCleanupItems": "Nenhum arquivo duplicado ou semelhante encontrado.",
  "save": "Salvar",
  "keep": "MANTER",
  "deselectAll": "Desmarcar todos",
  "images": "Imagens",
  "docs": "Documentos",
  "others": "Outros",
  "all": "Todos",
  "deleteConfirmMsg": "Tem certeza de que deseja excluir os {count} arquivos selecionados?\n\nOs itens serão movidos para a lixeira ou permanentemente excluídos.",
  "screenshotsCount": "{count, plural, =0{Nenhuma captura} =1{1 captura} other{{count} capturas}}",
  "selectedCountSize": "Selecionados: {count} ({size})",
  "deleteSelectedSize": "Excluir selecionados ({size})",
  "deleteFailedGeneral": "Falha ao excluir alguns itens.",
  "systemDefault": "Padrão do sistema",
  "light": "Claro",
  "dark": "Escuro",
  "strictSensitivity": "Estrito (Match 95%)",
  "normalSensitivity": "Normal (Match 85%)",
  "looseSensitivity": "Flexível (Match 75%)",
  "sensitivityDesc": "Escolha quão estritamente o aplicativo identifica fotos semelhantes.",
  "strictSensitivityDesc": "Match de 95% — Apenas quase idênticas",
  "normalSensitivityDesc": "Match de 85% — Recomendado",
  "looseSensitivityDesc": "Match de 75% — Captura mais variações",
  "sensitivityUpdated": "Configuração atualizada. Será aplicada na próxima varredura.",
  "thresholdDesc": "Arquivos maiores que esse valor serão marcados para limpeza.",
  "thresholdUpdated": "Limite atualizado. Será aplicado na próxima varredura.",
  "largerThanSize": "Maior que {size}",
  "madeWithHeart": "Feito com ❤️ para um celular mais limpo",
  "versionUnavailable": "Versão indisponível",
  "emailNotSupported": "Não foi possível abrir seu email.",
  "clearSpace": "Clear Space",
  "storageDashboard": "Armazenamento",
  "junkFilesFound": "Arquivos residuais encontrados",
  "itemsCanBeCleaned": "{count} itens a limpar",
  "storageBreakdown": "Detalhes de Uso",
  "cleanup": "Limpeza",
  "suggestions": "Sugestões",
  "analyzing": "Analisando...",
  "keepStorageHealthy": "Mantenha o sistema saudável",
  "cleanupHeaderDesc": "Encontramos arquivos que você pode remover para liberar espaço.",
  "percentUsed": "{percentage}% Usado",
  "scanPausedBattery": "Pausado (Bateria Franca)",
  "scanningPhase": "Verificando {phase}...",
  "scanningPhasePercent": "Verificando {phase}... ({percentage}%)",
  "calculating": "Calculando...",
  "internalStorage": "ARMAZENAMENTO INTERNO",
  "free": "Livre",
  "used": "Usado",
  "total": "Total",
  "phaseDisk": "Disco",
  "phasePhotos": "Fotos",
  "phaseVideos": "Vídeos",
  "phaseAudio": "Áudio",
  "phaseDocuments": "Docs",
  "phaseJunk": "Residuais",
  "phaseFolders": "Pastas",
  "phaseApks": "APKs",
  "phaseSimilar": "Fotos similares",
  "phaseStorage": "Memória",
  "selectYourLanguage": "Selecione seu Idioma",
  "largeFilesTitle": "Arquivos Grandes",
  "usedSize": "{size} Usado",
  "totalSize": "{size} Total",
  "clearHistory": "Limpar Histórico",
  "clearHistoryConfirm": "Tem certeza de que deseja limpar todo o histórico de uso?",
  "clearAll": "Limpar Tudo",
  "cleanAllSafeItems": "Limpar Restos Seguros"
};

Map<String, String> _fr() => {
  "refreshingAppList": "Actualisation...",
  "openingUninstaller": "Ouverture de la désinstallation...",
  "uninstallApp": "Désinstaller l'application",
  "uninstall": "Désinstaller",
  "sortLargest": "Plus gros",
  "sortSmallest": "Plus petit",
  "sortNewest": "Plus récents",
  "sortAZ": "A-Z",
  "pageNotFound": "Page introuvable",
  "goToDashboard": "Aller à l'accueil",
  "deleteFilesTitle": "Supprimer les fichiers",
  "smartCleanupPlanTitle": "Plan de nettoyage intelligent",
  "screenshotsCleanerTitle": "Nettoyage des captures",
  "tryAgain": "Réessayer",
  "appManagerTitle": "Gestionnaire d'applications",
  "searchApps": "Rechercher...",
  "noAppsFound": "Aucune application",
  "noMatchingApps": "Aucun résultat",
  "uninstallConfirmMsg": "Voulez-vous désinstaller \"{appName}\" ({size})?",
  "uninstallActionDesc": "L'application et ses données seront supprimées.",
  "appsCount": "{count} applications",
  "appsShowingCount": "{showing} / {total} applications",
  "allClean": "Tout propre !",
  "deleting": "Suppression...",
  "deleteItemsCount": "Supprimer {count} éléments ({size})",
  "deletedCountMsg": "{count} éléments supprimés ({size})",
  "actionCannotBeUndone": "Cette action est irréversible.",
  "cleanupBreakdown": "Bilan de nettoyage",
  "smartCleanupDesc": "Nous gardons automatiquement la meilleure version de vos fichiers.",
  "cleaning": "Nettoyage...",
  "cleanUpSize": "Nettoyer {size}",
  "youSavedSize": "Vous avez libéré {size}",
  "youreAllSet": "Tout est prêt !",
  "noSmartCleanupItems": "Aucun doublon trouvé.",
  "save": "Sauvegarder",
  "keep": "GARDER",
  "deselectAll": "Tout désélectionner",
  "images": "Images",
  "docs": "Docs",
  "others": "Autres",
  "all": "Tout",
  "deleteConfirmMsg": "Voulez-vous vraiment supprimer les fichiers sélectionnés ?",
  "screenshotsCount": "{count, plural, =0{Aucune} =1{1 capture} other{{count} captures}}",
  "selectedCountSize": "Sélection : {count} ({size})",
  "deleteSelectedSize": "Effacer la sélection ({size})",
  "deleteFailedGeneral": "Échec de suppression.",
  "systemDefault": "Système par défaut",
  "light": "Clair",
  "dark": "Sombre",
  "strictSensitivity": "Strict (Correspondance 95%)",
  "normalSensitivity": "Normal (Correspondance 85%)",
  "looseSensitivity": "Souple (Correspondance 75%)",
  "sensitivityDesc": "Choisissez comment les photos similaires sont identifiées.",
  "strictSensitivityDesc": "Seulement presque identiques",
  "normalSensitivityDesc": "Recommandé",
  "looseSensitivityDesc": "Variations plus larges",
  "sensitivityUpdated": "Paramètre de sensibilité mis à jour.",
  "thresholdDesc": "Fichiers plus grands que cette valeur ciblés.",
  "thresholdUpdated": "Seuil mis à jour.",
  "largerThanSize": "Supérieur à {size}",
  "madeWithHeart": "Fait avec ❤️ pour nettoyer votre mobile",
  "versionUnavailable": "Version non disponible",
  "emailNotSupported": "Action d'email non supportée.",
  "clearSpace": "Clear Space",
  "storageDashboard": "Tableau de Bord",
  "junkFilesFound": "Fichiers résiduels trouvés",
  "itemsCanBeCleaned": "{count} fichiers à nettoyer",
  "storageBreakdown": "Détail de l'espace",
  "cleanup": "Nettoyage",
  "suggestions": "Suggestions",
  "analyzing": "Analyse...",
  "keepStorageHealthy": "Gardez votre stockage à flot",
  "cleanupHeaderDesc": "Fichiers pouvant être supprimés.",
  "percentUsed": "{percentage}% Utilisé",
  "scanPausedBattery": "Analyse Pause (Batterie)",
  "scanningPhase": "Scanner {phase}...",
  "scanningPhasePercent": "Scanner {phase}... ({percentage}%)",
  "calculating": "Calcul...",
  "internalStorage": "STOCKAGE INTERNE",
  "free": "Libre",
  "used": "Utilisé",
  "total": "Total",
  "phaseDisk": "Disque",
  "phasePhotos": "Photos",
  "phaseVideos": "Vidéos",
  "phaseAudio": "Audio",
  "phaseDocuments": "Documents",
  "phaseJunk": "Résiduels",
  "phaseFolders": "Dossiers",
  "phaseApks": "APKs",
  "phaseSimilar": "Similaires",
  "phaseStorage": "Espace",
  "selectYourLanguage": "Sélectionnez votre Langue",
  "largeFilesTitle": "Fichiers Volumineux",
  "usedSize": "{size} Utilisé",
  "totalSize": "{size} Total",
  "clearHistory": "Effacer l'historique",
  "clearHistoryConfirm": "Voulez-vous réinitialiser le journal de nettoyage ?",
  "clearAll": "Tout effacer",
  "cleanAllSafeItems": "Nettoyage Inclus"
};

Map<String, String> _de() => {
  "refreshingAppList": "Aktualisiere App-Liste...",
  "openingUninstaller": "Öffne Deinstallationsprogramm...",
  "uninstallApp": "App deinstallieren",
  "uninstall": "Deinstallieren",
  "sortLargest": "Größte",
  "sortSmallest": "Kleinste",
  "sortNewest": "Neueste",
  "sortAZ": "A-Z",
  "pageNotFound": "Seite nicht gefunden",
  "goToDashboard": "Zum Dashboard",
  "deleteFilesTitle": "Dateien löschen",
  "smartCleanupPlanTitle": "Smart Cleanup Plan",
  "screenshotsCleanerTitle": "Screenshot-Reiniger",
  "tryAgain": "Erneut versuchen",
  "appManagerTitle": "App-Manager",
  "searchApps": "Apps suchen...",
  "noAppsFound": "Keine Apps gefunden",
  "noMatchingApps": "Keine Treffer",
  "uninstallConfirmMsg": "Möchten Sie \"{appName}\" ({size}) wirklich deinstallieren?",
  "uninstallActionDesc": "App und alle Daten werden entfernt.",
  "appsCount": "{count} Apps",
  "appsShowingCount": "{showing} / {total} Apps",
  "allClean": "Alles sauber!",
  "deleting": "Lösche...",
  "deleteItemsCount": "{count} Elemente löschen ({size})",
  "deletedCountMsg": "{count} Elemente gelöscht ({size})",
  "actionCannotBeUndone": "Dies kann nicht rückgängig gemacht werden.",
  "cleanupBreakdown": "Zusammenfassung",
  "smartCleanupDesc": "Beste Version wird automatisch behalten.",
  "cleaning": "Wird gereinigt...",
  "cleanUpSize": "{size} reinigen",
  "youSavedSize": "Sie haben {size} gespart",
  "youreAllSet": "Alles bereit!",
  "noSmartCleanupItems": "Keine Duplikate gefunden.",
  "save": "Speichern",
  "keep": "BEHALTEN",
  "deselectAll": "Alle abwählen",
  "images": "Bilder",
  "docs": "Dokumente",
  "others": "Andere",
  "all": "Alle",
  "deleteConfirmMsg": "Möchten Sie {count} Elemente wirklich löschen?",
  "screenshotsCount": "{count, plural, =0{Keine Screenshots} =1{1 Screenshot} other{{count} Screenshots}}",
  "selectedCountSize": "Ausgewählt: {count} ({size})",
  "deleteSelectedSize": "Auswahl löschen ({size})",
  "deleteFailedGeneral": "Löschen fehlgeschlagen.",
  "systemDefault": "Systemstandard",
  "light": "Hell",
  "dark": "Dunkel",
  "strictSensitivity": "Streng (95% Übereinstimmung)",
  "normalSensitivity": "Normal (85% Übereinstimmung)",
  "looseSensitivity": "Locker (75% Übereinstimmung)",
  "sensitivityDesc": "Wie streng ähnliche Fotos identifiziert werden sollen.",
  "strictSensitivityDesc": "Nur nahezu identisch",
  "normalSensitivityDesc": "Empfohlen",
  "looseSensitivityDesc": "Erfasst mehr Variationen",
  "sensitivityUpdated": "Empfindlichkeit aktualisiert.",
  "thresholdDesc": "Dateien über diesem Wert werden markiert.",
  "thresholdUpdated": "Schwellenwert aktualisiert.",
  "largerThanSize": "Größer als {size}",
  "madeWithHeart": "Gemacht mit ❤️ für ein sauberes Telefon",
  "versionUnavailable": "Version unerreichbar",
  "emailNotSupported": "E-Mail konnte nicht geöffnet werden.",
  "clearSpace": "Clear Space",
  "storageDashboard": "Speicher-Dashboard",
  "junkFilesFound": "Junk-Dateien gefunden",
  "itemsCanBeCleaned": "{count} Elemente reinigbar",
  "storageBreakdown": "Speichernutzung",
  "cleanup": "Reinigung",
  "suggestions": "Vorschläge",
  "analyzing": "Analysieren...",
  "keepStorageHealthy": "Speicher gesund halten",
  "cleanupHeaderDesc": "Gefundene Dateien zum Löschen.",
  "percentUsed": "{percentage}% genutzt",
  "scanPausedBattery": "Pause (Batterie schwach)",
  "scanningPhase": "Prüfe {phase}...",
  "scanningPhasePercent": "Prüfe {phase}... ({percentage}%)",
  "calculating": "Berechne...",
  "internalStorage": "INTERNER SPEICHER",
  "free": "Frei",
  "used": "Belegt",
  "total": "Gesamt",
  "phaseDisk": "Festplatte",
  "phasePhotos": "Fotos",
  "phaseVideos": "Videos",
  "phaseAudio": "Audio",
  "phaseDocuments": "Dokumente",
  "phaseJunk": "Junk-Dateien",
  "phaseFolders": "Ordner",
  "phaseApks": "APKs",
  "phaseSimilar": "Ähnliche Fotos",
  "phaseStorage": "Speicher",
  "selectYourLanguage": "Sprache wählen",
  "largeFilesTitle": "Große Dateien",
  "usedSize": "{size} belegt",
  "totalSize": "{size} total",
  "clearHistory": "Verlauf löschen",
  "clearHistoryConfirm": "Ganzen Reinigungsverlauf löschen?",
  "clearAll": "Alles löschen",
  "cleanAllSafeItems": "Alle sicheren Objekte reinigen"
};

Map<String, String> _tr() => {
  "refreshingAppList": "Uygulama listesi yenileniyor...",
  "openingUninstaller": "Kaldırıcı açılıyor...",
  "uninstallApp": "Uygulamayı Kaldır",
  "uninstall": "Kaldır",
  "sortLargest": "En büyük",
  "sortSmallest": "En küçük",
  "sortNewest": "En yeni",
  "sortAZ": "A'dan Z'ye",
  "pageNotFound": "Sayfa bulunamadı",
  "goToDashboard": "Panele Git",
  "deleteFilesTitle": "Dosyaları Sil",
  "smartCleanupPlanTitle": "Akıllı Temizlik Planı",
  "screenshotsCleanerTitle": "Ekran Görüntüsü Temizleyici",
  "tryAgain": "Tekrar dene",
  "appManagerTitle": "Uygulama Yöneticisi",
  "searchApps": "Uygulama ara...",
  "noAppsFound": "Uygulama bulunamadı",
  "noMatchingApps": "Eşleşen uygulama yok",
  "uninstallConfirmMsg": "\"{appName}\" ({size}) uygulamasını kaldırmak istiyor musunuz?",
  "uninstallActionDesc": "Uygulama ve tüm verileri silinecektir.",
  "appsCount": "{count} uygulama",
  "appsShowingCount": "{showing} / {total} uygulama gösteriliyor",
  "allClean": "Tertemiz!",
  "deleting": "Siliniyor...",
  "deleteItemsCount": "{count} öğeyi sil ({size})",
  "deletedCountMsg": "{count} öğe silindi ({size})",
  "actionCannotBeUndone": "Bu işlem geri alınamaz.",
  "cleanupBreakdown": "Temizlik Dağılımı",
  "smartCleanupDesc": "Benzer fotoğrafların ve dosyaların en iyi sürümünü otomatik tutuyoruz.",
  "cleaning": "Temizleniyor...",
  "cleanUpSize": "{size} Temizle",
  "youSavedSize": "{size} yer açtınız",
  "youreAllSet": "Her Şey Hazır!",
  "noSmartCleanupItems": "Hiç kopya dosya bulunamadı.",
  "save": "Kaydet",
  "keep": "TUT",
  "deselectAll": "Tümünü Kaldır",
  "images": "Resimler",
  "docs": "Belgeler",
  "others": "Diğer",
  "all": "Tümü",
  "deleteConfirmMsg": "Seçilen {count} dosyayı silmek istediğinizden emin misiniz?",
  "screenshotsCount": "{count, plural, =0{Ekran görüntüsü yok} =1{1 görüntü} other{{count} görüntü}}",
  "selectedCountSize": "Seçilen: {count} ({size})",
  "deleteSelectedSize": "Seçilenleri Sil ({size})",
  "deleteFailedGeneral": "Bazı öğeler silinemedi. Tekrar deneyin.",
  "systemDefault": "Sistem Varsayılanı",
  "light": "Açık",
  "dark": "Koyu",
  "strictSensitivity": "Katı (%95 Eşleşme)",
  "normalSensitivity": "Normal (%85 Eşleşme)",
  "looseSensitivity": "Gevşek (%75 Eşleşme)",
  "sensitivityDesc": "Uygulamanın benzer fotoğrafları nasıl tanımlayacağını seçin.",
  "strictSensitivityDesc": "Sadece neredeyse birebir aynı",
  "normalSensitivityDesc": "Önerilen ayar",
  "looseSensitivityDesc": "Daha fazla benzerlik bulur",
  "sensitivityUpdated": "Hassasiyet ayarı güncellendi.",
  "thresholdDesc": "Bu değerden büyük dosyalar işaretlenir.",
  "thresholdUpdated": "Limit güncellendi.",
  "largerThanSize": "{size} boyutundan büyük",
  "madeWithHeart": "Daha temiz bir telefon için ❤️ ile yapıldı",
  "versionUnavailable": "Sürüm yok",
  "emailNotSupported": "E-posta desteklenmiyor.",
  "clearSpace": "Clear Space",
  "storageDashboard": "Depolama Paneli",
  "junkFilesFound": "Gereksiz Dosyalar Bulundu",
  "itemsCanBeCleaned": "{count} öğe temizlenebilir",
  "storageBreakdown": "Depolama Kullanımı",
  "cleanup": "Temizlik",
  "suggestions": "Önerilenler",
  "analyzing": "İnceleniyor...",
  "keepStorageHealthy": "Depolamanızı koruyun",
  "cleanupHeaderDesc": "Yer açmak için silebileceğiniz dosyaları bulduk.",
  "percentUsed": "%{percentage} Dolu",
  "scanPausedBattery": "Tarama Durduruldu (Düşük Pil)",
  "scanningPhase": "Taranıyor: {phase}...",
  "scanningPhasePercent": "Taranıyor: {phase}... (%{percentage})",
  "calculating": "Hesaplanıyor...",
  "internalStorage": "DAHİLİ DEPOLAMA",
  "free": "Boş",
  "used": "Kullanılan",
  "total": "Toplam",
  "phaseDisk": "Disk",
  "phasePhotos": "Fotoğraflar",
  "phaseVideos": "Videolar",
  "phaseAudio": "Ses",
  "phaseDocuments": "Belgeler",
  "phaseJunk": "Gereksiz",
  "phaseFolders": "Klasörler",
  "phaseApks": "Kurulumlar",
  "phaseSimilar": "Benzer Resimler",
  "phaseStorage": "Depolama",
  "selectYourLanguage": "Dilinizi Seçin",
  "largeFilesTitle": "Büyük Dosyalar",
  "usedSize": "{size} Kullanımda",
  "totalSize": "{size} Toplam",
  "clearHistory": "Geçmişi Sil",
  "clearHistoryConfirm": "Temizlik geçmişini tamamen silmek istediğinizden emin misiniz?",
  "clearAll": "Tümünü Temizle",
  "cleanAllSafeItems": "Tüm Güvenli Öğeleri Temizle"
};

Map<String, String> _hi() => {
  "refreshingAppList": "ऐप सूची रीफ्रेश कर रहे हैं...",
  "openingUninstaller": "अनइंस्टालर खोल रहे हैं...",
  "uninstallApp": "ऐप अनइंस्टॉल करें",
  "uninstall": "अनइंस्टॉल",
  "sortLargest": "सबसे बड़ा पहलू",
  "sortSmallest": "सबसे छोटा पहलू",
  "sortNewest": "नवीनतम",
  "sortAZ": "A से Z",
  "pageNotFound": "पृष्ठ नहीं मिला",
  "goToDashboard": "डैशबोर्ड पर जाएं",
  "deleteFilesTitle": "फ़ाइलें हटा दें",
  "smartCleanupPlanTitle": "स्मार्ट सफाई योजना",
  "screenshotsCleanerTitle": "स्क्रीनशॉट क्लीनर",
  "tryAgain": "फिर से प्रयास करें",
  "appManagerTitle": "ऐप प्रबंधक",
  "searchApps": "ऐप खोजें...",
  "noAppsFound": "कोई ऐप नहीं मिला",
  "noMatchingApps": "कोई संबंधित ऐप नहीं",
  "uninstallConfirmMsg": "क्या आप निश्चित रूप से \"{appName}\" ({size}) अनइंस्टॉल करना चाहते हैं?",
  "uninstallActionDesc": "यह ऐप और उसका सारा डेटा मिटा देगा।",
  "appsCount": "{count} ऐप्स",
  "appsShowingCount": "{showing} / {total} ऐप्स",
  "allClean": "सब कुछ साफ़ है!",
  "deleting": "हटा रहे हैं...",
  "deleteItemsCount": "{count} आइटम हटाएं ({size})",
  "deletedCountMsg": "{count} आइटम हटाए गए ({size})",
  "actionCannotBeUndone": "इस क्रिया को पूर्ववत नहीं किया जा सकता।",
  "cleanupBreakdown": "सफाई विवरण",
  "smartCleanupDesc": "हम स्वचालित रूप से आपकी फ़ोटो का सबसे अच्छा संस्करण रखते हैं।",
  "cleaning": "सफाई हो रही है...",
  "cleanUpSize": "{size} खाली करें",
  "youSavedSize": "आपने {size} बचाया",
  "youreAllSet": "सब कुछ तैयार है!",
  "noSmartCleanupItems": "कोई डुप्लिकेट नहीं मिला।",
  "save": "बचाएं",
  "keep": "रखें",
  "deselectAll": "सब चुनी हुई हटाएँ",
  "images": "इमेजेज",
  "docs": "दस्तावेज़",
  "others": "अन्य",
  "all": "सभी",
  "deleteConfirmMsg": "क्या आप चुने गए {count} दस्तावेज़ मिटाना चाहते हैं?",
  "screenshotsCount": "{count, plural, =0{कोई स्क्रीनशॉट नहीं} =1{1 स्क्रीनशॉट} other{{count} स्क्रीनशॉट}}",
  "selectedCountSize": "चुना हुआ: {count} ({size})",
  "deleteSelectedSize": "चुने गए आइटम हटाएँ ({size})",
  "deleteFailedGeneral": "कुछ आइटम हटाने में विफल रहे। पुनः प्रयास करें।",
  "systemDefault": "सिस्टम डिफ़ॉल्ट",
  "light": "हल्का",
  "dark": "गहरा",
  "strictSensitivity": "सख्त (95% मिलान)",
  "normalSensitivity": "सामान्य (85% मिलान)",
  "looseSensitivity": "लचीला (75% मिलान)",
  "sensitivityDesc": "चुनें कि ऐप कितनी सख्ती से समान फ़ोटो पहचानता है।",
  "strictSensitivityDesc": "सख्त — लगभग एकदम समान तस्वीर",
  "normalSensitivityDesc": "सामान्य — प्रमाणित उपयोग",
  "looseSensitivityDesc": "ढीला — अधिक तस्वीरें पकड़ेगा",
  "sensitivityUpdated": "संवेदनशीलता अद्यतित की गई।",
  "thresholdDesc": "इस आकार से बड़ी फाइलें हटाने के लिए चिह्नित होंगी।",
  "thresholdUpdated": "सीमा अद्यतित की गई।",
  "largerThanSize": "{size} से बड़ी",
  "madeWithHeart": "साफ़ फ़ोन के लिए ❤️ से बना",
  "versionUnavailable": "संस्करण अनुपलब्ध",
  "emailNotSupported": "ईमेल ग्राहक नहीं खुला।",
  "clearSpace": "Clear Space",
  "storageDashboard": "स्टोरेज डैशबोर्ड",
  "junkFilesFound": "कचरा फ़ाइलें मिलीं",
  "itemsCanBeCleaned": "{count} आइटम साफ़ हो सकते हैं",
  "storageBreakdown": "स्टोरेज उपयोग",
  "cleanup": "सफाई करें",
  "suggestions": "सुझाव",
  "analyzing": "विश्लेषण...",
  "keepStorageHealthy": "स्थान को स्वस्थ रखें",
  "cleanupHeaderDesc": "स्थान खाली करने वाले दस्तावेज़।",
  "percentUsed": "{percentage}% उपयोग",
  "scanPausedBattery": "रुक गया (कम बैटरी)",
  "scanningPhase": "स्कैनिंग {phase}...",
  "scanningPhasePercent": "स्कैनिंग {phase}... ({percentage}%)",
  "calculating": "मूल्यांकन कर रहे हैं...",
  "internalStorage": "इंटरनल स्टोरेज",
  "free": "खाली",
  "used": "भरा हुआ",
  "total": "कुल",
  "phaseDisk": "डिस्क",
  "phasePhotos": "चित्र",
  "phaseVideos": "वीडियो",
  "phaseAudio": "संगीत",
  "phaseDocuments": "दस्तावेज़",
  "phaseJunk": "जंक",
  "phaseFolders": "फोल्डर",
  "phaseApks": "APKs",
  "phaseSimilar": "समान तस्वीरें",
  "phaseStorage": "स्टोरेज",
  "selectYourLanguage": "अपनी भाषा चुनें",
  "largeFilesTitle": "बड़ी फ़ाइलें",
  "usedSize": "{size} उपयोग",
  "totalSize": "{size} कुल",
  "clearHistory": "इतिहास मिटाएँ",
  "clearHistoryConfirm": "क्या आप पूरा इतिहास मिटाना चाहते हैं?",
  "clearAll": "सब साफ़ करें",
  "cleanAllSafeItems": "सुरक्षित साफ़ करें"
};

Map<String, String> _id() => {
  "refreshingAppList": "Menyegarkan daftar aplikasi...",
  "openingUninstaller": "Membuka pencopot pemasangan...",
  "uninstallApp": "Copot Aplikasi",
  "uninstall": "Copot Pemasangan",
  "sortLargest": "Terbesar",
  "sortSmallest": "Terkecil",
  "sortNewest": "Terbaru",
  "sortAZ": "A-Z",
  "pageNotFound": "Halaman Tidak Ditemukan",
  "goToDashboard": "Ke Dasbor",
  "deleteFilesTitle": "Hapus File",
  "smartCleanupPlanTitle": "Rencana Pembersihan Pintar",
  "screenshotsCleanerTitle": "Pembersih Tangkapan Layar",
  "tryAgain": "Coba Lagi",
  "appManagerTitle": "Manajer Aplikasi",
  "searchApps": "Cari aplikasi...",
  "noAppsFound": "Tidak ada aplikasi",
  "noMatchingApps": "Tidak ada aplikasi cocok",
  "uninstallConfirmMsg": "Apakah Anda yakin ingin mencopot \"{appName}\" ({size})?",
  "uninstallActionDesc": "Ini akan menghapus aplikasi dan semua datanya.",
  "appsCount": "{count} aplikasi",
  "appsShowingCount": "{showing} / {total} aplikasi",
  "allClean": "Semua bersih!",
  "deleting": "Menghapus...",
  "deleteItemsCount": "Hapus {count} item ({size})",
  "deletedCountMsg": "{count} item dihapus ({size})",
  "actionCannotBeUndone": "Tindakan tak dapat dibatalkan.",
  "cleanupBreakdown": "Rincian Pembersihan",
  "smartCleanupDesc": "Kami secara otomatis menyimpan versi terbaik foto dan file Anda.",
  "cleaning": "Membersihkan...",
  "cleanUpSize": "Bersihkan {size}",
  "youSavedSize": "Anda menghemat {size}",
  "youreAllSet": "Semuanya Beres!",
  "noSmartCleanupItems": "Tidak ditemukan file duplikat.",
  "save": "Simpan",
  "keep": "SIMPAN",
  "deselectAll": "Batalkan Pilihan Semua",
  "images": "Gambar",
  "docs": "Dokumen",
  "others": "Lainnya",
  "all": "Semua",
  "deleteConfirmMsg": "Apakah Anda yakin ingin menghapus {count} file yang dipilih?\n\nFile akan dihapus secara permanen.",
  "screenshotsCount": "{count, plural, =0{Tidak ada tangkapan layar} =1{1 tangkapan layar} other{{count} tangkapan layar}}",
  "selectedCountSize": "Terpilih: {count} ({size})",
  "deleteSelectedSize": "Hapus Terpilih ({size})",
  "deleteFailedGeneral": "Gagal menghapus file. Coba lagi.",
  "systemDefault": "Standar Sistem",
  "light": "Terang",
  "dark": "Gelap",
  "strictSensitivity": "Ketat (Cocok 95%)",
  "normalSensitivity": "Normal (Cocok 85%)",
  "looseSensitivity": "Longgar (Cocok 75%)",
  "sensitivityDesc": "Seberapa ketat aplikasi saat mengidentifikasi foto serupa.",
  "strictSensitivityDesc": "Ketat — Hanya yang sangat mirip",
  "normalSensitivityDesc": "Normal — Disarankan",
  "looseSensitivityDesc": "Longgar — Banyak variasi foto",
  "sensitivityUpdated": "Sensitivitas diperbarui. Akan digunakan pada pemindaian berikutnya.",
  "thresholdDesc": "File lebih besar dari ini akan ditandai untuk dihapus.",
  "thresholdUpdated": "Batas diperbarui. Akan digunakan pada pemindaian berikutnya.",
  "largerThanSize": "Lebih besar dari {size}",
  "madeWithHeart": "Dibuat dengan ❤️ untuk ponsel yang lebih bersih",
  "versionUnavailable": "Versi tidak tersedia",
  "emailNotSupported": "Gagal membuka email.",
  "clearSpace": "Clear Space",
  "storageDashboard": "Dasbor Penyimpanan",
  "junkFilesFound": "File Sampah Ditemukan",
  "itemsCanBeCleaned": "{count} item siap dibersihkan",
  "storageBreakdown": "Rincian Penyimpanan",
  "cleanup": "Pembersihan",
  "suggestions": "Saran",
  "analyzing": "Menganalisis...",
  "keepStorageHealthy": "Jaga ruang ponsel Anda",
  "cleanupHeaderDesc": "File ini dapat dihapus untuk ruang kosong.",
  "percentUsed": "{percentage}% Digunakan",
  "scanPausedBattery": "Jeda (Baterai Lemah)",
  "scanningPhase": "Memindai {phase}...",
  "scanningPhasePercent": "Memindai {phase}... ({percentage}%)",
  "calculating": "Menghitung...",
  "internalStorage": "PENYIMPANAN INTERNAL",
  "free": "Kosong",
  "used": "Digunakan",
  "total": "Total",
  "phaseDisk": "Disk",
  "phasePhotos": "Foto",
  "phaseVideos": "Video",
  "phaseAudio": "Audio",
  "phaseDocuments": "Dokumen",
  "phaseJunk": "Berkas Sampah",
  "phaseFolders": "Folder",
  "phaseApks": "APK",
  "phaseSimilar": "Foto Mirip",
  "phaseStorage": "Penyimpanan",
  "selectYourLanguage": "Pilih Bahasa",
  "largeFilesTitle": "File Besar",
  "usedSize": "{size} Digunakan",
  "totalSize": "{size} Total",
  "clearHistory": "Bersihkan Riwayat",
  "clearHistoryConfirm": "Yakin ingin bersihkan riwayat pembersihan?",
  "clearAll": "Bersihkan Semua",
  "cleanAllSafeItems": "Bersihkan Barang Aman"
};

Map<String, String> _fil() => {
  "refreshingAppList": "Nire-refresh ang apps...",
  "openingUninstaller": "Binubuksan ang uninstaller...",
  "uninstallApp": "I-uninstall ang App",
  "uninstall": "I-uninstall",
  "sortLargest": "Pinakamalaki",
  "sortSmallest": "Pinakamaliit",
  "sortNewest": "Pinakabago",
  "sortAZ": "A-Z",
  "pageNotFound": "Pahina Hindi Nahanap",
  "goToDashboard": "Pumunta sa Dashboard",
  "deleteFilesTitle": "Burahin ang Files",
  "smartCleanupPlanTitle": "Smart na Plano",
  "screenshotsCleanerTitle": "Screenshot Cleaner",
  "tryAgain": "Subukang muli",
  "appManagerTitle": "App Manager",
  "searchApps": "Maghanap ng app...",
  "noAppsFound": "Walang nakitang apps",
  "noMatchingApps": "Walang tumugma",
  "uninstallConfirmMsg": "Sigurado ka bang i-uninstall ang \"{appName}\" ({size})?",
  "uninstallActionDesc": "Tatanggalin nito ang app at ang data.",
  "appsCount": "{count} apps",
  "appsShowingCount": "{showing} / {total} apps",
  "allClean": "Lahat malinis!",
  "deleting": "Binubura...",
  "deleteItemsCount": "Burahin {count} aytem ({size})",
  "deletedCountMsg": "Nabura ang {count} aytem ({size})",
  "actionCannotBeUndone": "Hindi na babalik ang nabura.",
  "cleanupBreakdown": "Bahagi ng Nilinis",
  "smartCleanupDesc": "Pinapanatili ang pinakamagandang kuha ng mga litrato mo.",
  "cleaning": "Naglilinis...",
  "cleanUpSize": "Linisin {size}",
  "youSavedSize": "Nakatipid ka ng {size}",
  "youreAllSet": "Handa na lahat!",
  "noSmartCleanupItems": "Walang duplicate na nakita.",
  "save": "I-save",
  "keep": "PANATILIHIN",
  "deselectAll": "Tanggalin ang Pili Lahat",
  "images": "Mga Larawan",
  "docs": "Dokumento",
  "others": "Iba pa",
  "all": "Lahat",
  "deleteConfirmMsg": "Sigurado ka bang buburahin ang {count} file?\n\nAng mga ito ay permenenteng mbubura.",
  "screenshotsCount": "{count, plural, =0{Walang screenshots} =1{1 screenshot} other{{count} screenshots}}",
  "selectedCountSize": "Pinili: {count} ({size})",
  "deleteSelectedSize": "Burahin ang Napili ({size})",
  "deleteFailedGeneral": "Bigo na burahin ang ilang files.",
  "systemDefault": "System Default",
  "light": "Liwanag",
  "dark": "Dilim",
  "strictSensitivity": "Mahigpit (95% Match)",
  "normalSensitivity": "Normal (85% Match)",
  "looseSensitivity": "Maluwag (75% Match)",
  "sensitivityDesc": "Gaano kahigpit kukunin ng app ang magkaparehong mga larawan.",
  "strictSensitivityDesc": "Mahigpit — Ang halos saktong pareho lang",
  "normalSensitivityDesc": "Normal — Para sa inyo",
  "looseSensitivityDesc": "Maluwag — Higit pang makukuha",
  "sensitivityUpdated": "Pagbabago nakasave. Gagamitin ito sa susunod.",
  "thresholdDesc": "Ang mga file na mas malaki dito ay makukuha.",
  "thresholdUpdated": "Limitasyon nakasave.",
  "largerThanSize": "Mas malaki sa {size}",
  "madeWithHeart": "Ginawa may pagmamahal ❤️",
  "versionUnavailable": "Bersyon hindi handa",
  "emailNotSupported": "Email system walang galaw.",
  "clearSpace": "Clear Space",
  "storageDashboard": "Imbakang Dasboard",
  "junkFilesFound": "Mga Basurang Nahanap",
  "itemsCanBeCleaned": "{count} aytem pwedeng linisin",
  "storageBreakdown": "Lagayan Ng Espasyo",
  "cleanup": "Linisin",
  "suggestions": "Pangyayari",
  "analyzing": "Nagsusuri...",
  "keepStorageHealthy": "Gawing Mabilis ang Phone Mo",
  "cleanupHeaderDesc": "Files pwedeng tanggalin upang makatipid.",
  "percentUsed": "{percentage}% Ginamit",
  "scanPausedBattery": "Tumigil (Low Battery)",
  "scanningPhase": "Sinasakan: {phase}...",
  "scanningPhasePercent": "Sinasakan: {phase}... ({percentage}%)",
  "calculating": "Kinakalkula...",
  "internalStorage": "PANLOOB NA ESPASYO",
  "free": "Libre",
  "used": "Ginamit",
  "total": "Lahat",
  "phaseDisk": "Disk",
  "phasePhotos": "Larawan",
  "phaseVideos": "Mga Video",
  "phaseAudio": "Music",
  "phaseDocuments": "Dokumento",
  "phaseJunk": "Mga Basura",
  "phaseFolders": "Folders",
  "phaseApks": "Mga APKs",
  "phaseSimilar": "Dobleng Larawan",
  "phaseStorage": "Bara",
  "selectYourLanguage": "Piliin ang Lenggwahe",
  "largeFilesTitle": "Malalaking File",
  "usedSize": "Ginamit na {size}",
  "totalSize": "Lahat {size}",
  "clearHistory": "Burahin ang Record",
  "clearHistoryConfirm": "Sigurado ka ba burahin ang record na paglilinis?",
  "clearAll": "Burahin Lahat",
  "cleanAllSafeItems": "Linisin ang Pwedeng Linisin"
};
