#!/usr/bin/env bash
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
GRAY='\033[0;90m'
NC='\033[0m'

step() { echo -e "\n${CYAN}==> $1${NC}"; }
ok() { echo -e "${GREEN}[OK] $1${NC}"; }
fail() { echo -e "${RED}[ERROR] $1${NC}"; }
warn() { echo -e "${YELLOW}[WARN] $1${NC}"; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "${SCRIPT_DIR}")"
APP_DIR="${PROJECT_ROOT}"
ANDROID_DIR="${APP_DIR}/android"
KEYSTORE_DIR="${ANDROID_DIR}/keystore"
KEYSTORE_FILE_NAME="upload-keystore.jks"
KEYSTORE_PATH="${KEYSTORE_DIR}/${KEYSTORE_FILE_NAME}"
KEY_PROPERTIES_PATH="${ANDROID_DIR}/key.properties"
RELATIVE_KEYSTORE_PATH="../keystore/${KEYSTORE_FILE_NAME}"

echo
echo -e "${MAGENTA}============================================${NC}"
echo -e "${MAGENTA}  Clean Master Space - Android Keystore Generator${NC}"
echo -e "${MAGENTA}============================================${NC}"
echo

step "Checking keytool"
KEYTOOL=""
if [[ -n "${JAVA_HOME:-}" && -f "${JAVA_HOME}/bin/keytool" ]]; then
  KEYTOOL="${JAVA_HOME}/bin/keytool"
elif command -v keytool >/dev/null 2>&1; then
  KEYTOOL="$(command -v keytool)"
elif [[ -f "/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/keytool" ]]; then
  KEYTOOL="/Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/keytool"
fi

if [[ -z "${KEYTOOL}" ]]; then
  fail "keytool not found. Install JDK or set JAVA_HOME."
  exit 1
fi
ok "Using keytool: ${KEYTOOL}"

if [[ -f "${KEYSTORE_PATH}" ]]; then
  warn "Keystore already exists at ${KEYSTORE_PATH}"
  read -r -p "Overwrite? (y/N) " OVERWRITE
  if [[ ! "${OVERWRITE}" =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 0
  fi
fi

mkdir -p "${KEYSTORE_DIR}"

echo
echo -e "${GRAY}Press Enter to accept defaults.${NC}"
echo

DEFAULT_ALIAS="cleanmasterspace_upload"
read -r -p "Key alias [${DEFAULT_ALIAS}]: " ALIAS
ALIAS="${ALIAS:-${DEFAULT_ALIAS}}"

while true; do
  read -r -s -p "Keystore password: " STORE_PASSWORD
  echo
  if [[ ${#STORE_PASSWORD} -lt 6 ]]; then
    warn "Password must be at least 6 characters."
    continue
  fi
  read -r -s -p "Confirm keystore password: " CONFIRM_STORE_PASSWORD
  echo
  if [[ "${STORE_PASSWORD}" != "${CONFIRM_STORE_PASSWORD}" ]]; then
    warn "Passwords do not match."
    continue
  fi
  break
done

KEY_PASSWORD="${STORE_PASSWORD}"
read -r -p "Use same password for key? (Y/n) " USE_SAME
if [[ "${USE_SAME}" =~ ^[Nn]$ ]]; then
  while true; do
    read -r -s -p "Key password: " KEY_PASSWORD
    echo
    read -r -s -p "Confirm key password: " CONFIRM_KEY_PASSWORD
    echo
    if [[ "${KEY_PASSWORD}" != "${CONFIRM_KEY_PASSWORD}" ]]; then
      warn "Passwords do not match."
      continue
    fi
    break
  done
fi

DEFAULT_CN="Clean Master Space"
read -r -p "App/Owner name [${DEFAULT_CN}]: " CN
CN="${CN:-${DEFAULT_CN}}"

DEFAULT_OU="Mobile"
read -r -p "Organizational unit [${DEFAULT_OU}]: " OU
OU="${OU:-${DEFAULT_OU}}"

DEFAULT_O="Movixa Labs"
read -r -p "Organization [${DEFAULT_O}]: " O
O="${O:-${DEFAULT_O}}"

DEFAULT_L="Ho Chi Minh City"
read -r -p "City [${DEFAULT_L}]: " L
L="${L:-${DEFAULT_L}}"

DEFAULT_S="Ho Chi Minh"
read -r -p "State/Province [${DEFAULT_S}]: " S
S="${S:-${DEFAULT_S}}"

DEFAULT_C="VN"
read -r -p "Country code [${DEFAULT_C}]: " C
C="${C:-${DEFAULT_C}}"

DEFAULT_VALIDITY="10000"
read -r -p "Validity in days [${DEFAULT_VALIDITY}]: " VALIDITY
VALIDITY="${VALIDITY:-${DEFAULT_VALIDITY}}"

DNAME="CN=${CN}, OU=${OU}, O=${O}, L=${L}, ST=${S}, C=${C}"

echo
echo -e "${CYAN}Summary:${NC}"
echo "  keystore: ${KEYSTORE_PATH}"
echo "  alias:    ${ALIAS}"
echo "  dname:    ${DNAME}"
echo "  validity: ${VALIDITY}"
echo
read -r -p "Generate now? (Y/n) " CONFIRM
if [[ "${CONFIRM}" =~ ^[Nn]$ ]]; then
  echo "Aborted."
  exit 0
fi

step "Generating keystore"
# Remove old keystore to avoid 'alias already exists' error
rm -f "${KEYSTORE_PATH}"
"${KEYTOOL}" -genkeypair -v \
  -keystore "${KEYSTORE_PATH}" \
  -alias "${ALIAS}" \
  -keyalg RSA \
  -keysize 2048 \
  -validity "${VALIDITY}" \
  -storepass "${STORE_PASSWORD}" \
  -keypass "${KEY_PASSWORD}" \
  -dname "${DNAME}" \
  -noprompt

if [[ ! -f "${KEYSTORE_PATH}" ]]; then
  fail "Keystore file was not created."
  exit 1
fi
ok "Keystore created."

step "Writing key.properties"
cat > "${KEY_PROPERTIES_PATH}" <<EOF
# Auto-generated by scripts/create-keystore.sh
# Generated on: $(date '+%Y-%m-%d %H:%M:%S')

storeFile=${RELATIVE_KEYSTORE_PATH}
storePassword=${STORE_PASSWORD}
keyAlias=${ALIAS}
keyPassword=${KEY_PASSWORD}
EOF

printf '*\n!.gitignore' > "${KEYSTORE_DIR}/.gitignore"

ok "key.properties created: ${KEY_PROPERTIES_PATH}"
echo
echo -e "${GREEN}Done. Keep keystore and passwords backed up safely.${NC}"
echo -e "${YELLOW}Build command: ./scripts/build-release.sh${NC}"
